/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Chair.gltf -o .\src\components\models\Chair.jsx -r public -k --shadows 
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { radToDeg } from 'three/src/math/MathUtils.js';

export function Chair(props) {
  const chairRef = useRef()
  const { nodes, materials } = useGLTF('/models/Chair.gltf');

  useEffect(() => {
    gsap.to(chairRef.current.rotation, {
      y: radToDeg(-Math.PI / 8),
      duration: 300,
      repeat: -1,
      ease: 'none'
    });
  }, []);
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Chair001" castShadow geometry={nodes.Chair001.geometry} material={materials['Chair feet']} position={[-1.679, 2.399, 0.848]} rotation={[0, Math.PI / 4, 0]} scale={0.671} />
        <mesh ref={chairRef} name="Cube034" castShadow geometry={nodes.Cube034.geometry} material={materials.Material} position={[-1.674, 1.545, 0.881]} rotation={[0, Math.PI / 4, 0]} scale={0.671} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Chair.gltf')
